### ISSUE TITLE
Run all benchmarks

### ISSUE THREAD

**Issue by RafaelGSS** [RafaelGSS/nodejs-bench-operations#42]
@H4ad After merging #41, the benchmark results were cleaned and we'd need to manually re-run all the benchmarks again. We should have an action to populate everything. That's necessary whenever the dedicated machine changes the hardware.

**Comment by H4ad** [comment]
I initially planned an action to do that but I totally forgot during the implementation.

But I can create a PR in the next few days to do that, to avoid doing it manually.

I'm not sure how I will achieve such integration, but I can think in two options:

- Create a script to generate a GitHub action that calls "Run Benchmarks" for each benchmark.
- Create a GitHub action to run all the benchmarks sequentially, by node version, and then commit the results.

I cannot use GitHub matrix because of the limit, the first option is easy but not so "good", and the second one took more time to create, do you have any suggestions?

**Comment by RafaelGSS** [comment]
I'd go with 1 for simplicity.
